// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectToServer(arg1:number):Promise<void>;

export function Delete(arg1:Array<string>):Promise<void>;

export function Download(arg1:string,arg2:Array<string>):Promise<void>;

export function DownloadADB():Promise<string>;

export function GetDefaultSettings():Promise<main.DefaultSettings>;

export function GetDeviceList():Promise<Array<string>>;

export function GetShortcutPaths():Promise<Array<string>>;

export function KillServer(arg1:string,arg2:number):Promise<void>;

export function List(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.DirEntries>;

export function MakeDir(arg1:string,arg2:string):Promise<void>;

export function NewADBClient(arg1:string,arg2:number):Promise<void>;

export function Rename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectADBExecutable():Promise<string>;

export function SelectDevice(arg1:number,arg2:string):Promise<void>;

export function SelectDownloadDir():Promise<string>;

export function Upload(arg1:string,arg2:string):Promise<void>;
