// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToServer(arg1) {
  return window['go']['main']['App']['ConnectToServer'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function Download(arg1, arg2) {
  return window['go']['main']['App']['Download'](arg1, arg2);
}

export function DownloadADB() {
  return window['go']['main']['App']['DownloadADB']();
}

export function GetDefaultSettings() {
  return window['go']['main']['App']['GetDefaultSettings']();
}

export function GetDeviceList() {
  return window['go']['main']['App']['GetDeviceList']();
}

export function GetShortcutPaths() {
  return window['go']['main']['App']['GetShortcutPaths']();
}

export function KillServer(arg1, arg2) {
  return window['go']['main']['App']['KillServer'](arg1, arg2);
}

export function List(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['List'](arg1, arg2, arg3, arg4);
}

export function MakeDir(arg1, arg2) {
  return window['go']['main']['App']['MakeDir'](arg1, arg2);
}

export function NewADBClient(arg1, arg2) {
  return window['go']['main']['App']['NewADBClient'](arg1, arg2);
}

export function Rename(arg1, arg2, arg3) {
  return window['go']['main']['App']['Rename'](arg1, arg2, arg3);
}

export function SelectADBExecutable() {
  return window['go']['main']['App']['SelectADBExecutable']();
}

export function SelectDevice(arg1, arg2) {
  return window['go']['main']['App']['SelectDevice'](arg1, arg2);
}

export function SelectDownloadDir() {
  return window['go']['main']['App']['SelectDownloadDir']();
}

export function Upload(arg1, arg2) {
  return window['go']['main']['App']['Upload'](arg1, arg2);
}
